export const ENDPOINTS = {
  app: {
    getHello: '/',
  },
  auth: {
    register: '/auth/register',
    verifyEmail: '/auth/verify-email',
    resendVerification: '/auth/resend-verification',
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    resetPasswordRequest: '/auth/reset-password-request',
    resetPassword: '/auth/reset-password',
  },
  users: {
    list: '/users',
    create: '/users',
    detail: (id: string) => `/users/${id}`,
    update: (id: string) => `/users/${id}`,
    delete: (id: string) => `/users/${id}`,
    address: '/users/address',
  },
  categories: {
    list: '/categories',
    create: '/categories',
    detail: (id: string) => `/categories/${id}`,
    update: (id: string) => `/categories/${id}`,
    delete: (id: string) => `/categories/${id}`,
  },
  products: {
    list: '/products',
    mine: '/products/me',
    create: (categoryId: string) => `/products/${categoryId}`,
    detail: (id: string) => `/products/${id}`,
    update: (id: string) => `/products/${id}`,
    adjustStock: (id: string) => `/products/${id}/stock`,
    delete: (id: string) => `/products/${id}`,
  },
  shops: {
    me: '/shops/me',
    list: '/shops',
    create: '/shops',
    detail: (id: string) => `/shops/${id}`,
    update: (id: string) => `/shops/${id}`,
    delete: (id: string) => `/shops/${id}`,
  },
  cart: {
    list: '/cart',
    mine: '/cart/mine',
    addItem: (productId: string) => `/cart/${productId}`,
    detail: (id: string) => `/cart/${id}`,
    updateItem: (id: string) => `/cart/${id}`,
    removeItem: (id: string) => `/cart/${id}`,
  },
  orders: {
    list: '/orders',
    detail: (id: string) => `/orders/${id}`,
    invoice: (id: string) => `/orders/${id}/invoice`,
    update: (id: string) => `/orders/${id}`,
  },
  payments: {
    list: '/payments',
    me: '/payments/me',
    create: (cartId: string) => `/payments/${cartId}`,
    detail: (id: string) => `/payments/${id}`,
    update: (id: string) => `/payments/${id}`,
    cancel: (id: string) => `/payments/${id}`,
  },
  reviews: {
    list: '/reviews',
    create: (productId: string) => `/reviews/${productId}`,
    detail: (id: string) => `/reviews/${id}`,
    update: (id: string) => `/reviews/${id}`,
    delete: (id: string) => `/reviews/${id}`,
  },
  notifications: {
    list: '/notifications',
    unreadCount: '/notifications/unread-count',
    readAll: '/notifications/read-all',
    read: (id: string) => `/notifications/${id}/read`,
  },
  dashboards: {
    admin: '/admin/dashboard',
    supplier: '/supplier/dashboard',
  },
} as const;
